apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-latest-tag
  name: nginx-latest-tag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-latest-tag
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-latest-tag
    spec:
      containers:
      - image: nginx:latest
        name: nginx
        resources: {}
status: {}
